import React, { useRef, useState } from 'react';
import { useHealth } from '../../context/HealthContext';
import {
  FileText,
  Printer,
  Download,
  Copy,
  Check,
  X,
  Share2,
  HeartPulse,
  User,
  Utensils,
  Flame,
  Droplets,
  Moon,
  Target,
  Sparkles,
  Award
} from 'lucide-react';
import confetti from 'canvas-confetti';

interface DailyReportModalProps {
  onClose: () => void;
}

export const DailyReportModal: React.FC<DailyReportModalProps> = ({ onClose }) => {
  const {
    profile,
    bmiData,
    exercises,
    totalExerciseMinutes,
    totalCaloriesBurned,
    sleepRecord,
    waterLogs,
    totalWaterMl,
    totalNutrition,
    goals,
    dailyHealthScore
  } = useHealth();

  const [copied, setCopied] = useState(false);
  const reportRef = useRef<HTMLDivElement>(null);

  // Goal statuses: ✅ or ⚠️
  const waterGoalMet = totalWaterMl >= (goals.waterMl * 0.75);
  const exerciseGoalMet = totalExerciseMinutes >= goals.exerciseMinutes;
  const sleepGoalMet = sleepRecord.totalHours >= (goals.sleepHours - 0.5);
  const calRatio = totalNutrition.calories / (goals.caloriesTarget || 1800);
  const nutritionGoalMet = calRatio >= 0.8 && calRatio <= 1.15;

  const formattedDate = new Date().toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });

  const waterL = (totalWaterMl / 1000).toFixed(1);
  const goalWaterL = (goals.waterMl / 1000).toFixed(1);
  const waterPct = Math.round((totalWaterMl / goals.waterMl) * 100);

  const handlePrint = () => {
    window.print();
  };

  const handleCopyReport = () => {
    const textReport = `
🌿 NutriFit - Daily Health Report
Date: ${formattedDate}

👤 Personal Information
Name: ${profile.name}
Age: ${profile.age}
Height: ${profile.height} cm
Weight: ${profile.weight} kg
BMI: ${bmiData.bmi} (${bmiData.category})

🥗 Nutrition
Calories Consumed: ${totalNutrition.calories} kcal
Protein: ${totalNutrition.protein} g
Carbohydrates: ${totalNutrition.carbs} g
Fat: ${totalNutrition.fat} g

🏃 Activity
${exercises.map(e => `${e.exerciseName}: ${e.durationMinutes} min — ${e.caloriesBurned} kcal`).join('\n')}
Total Activity: ${totalExerciseMinutes} minutes
Estimated Calories Burned: ${totalCaloriesBurned} kcal

💧 Hydration
Water Intake: ${waterL} L / ${goalWaterL} L
${waterPct}% of goal achieved

😴 Sleep
Sleep Duration: ${sleepRecord.hours}h ${sleepRecord.minutes}m (${sleepRecord.bedtime} to ${sleepRecord.wakeTime})

🎯 Daily Goals
Water: ${waterGoalMet ? '✅' : '⚠️'}
Exercise: ${exerciseGoalMet ? '✅' : '⚠️'}
Sleep: ${sleepGoalMet ? '✅' : '⚠️'}
Nutrition: ${nutritionGoalMet ? '✅' : '⚠️'}

📊 Overall Progress
Daily Health Score: ${dailyHealthScore}%
Summary Feedback: Great job! You maintained good activity and hydration today. Try to stay consistent with your nutrition goals.
Report ID: NFT-${Date.now().toString().slice(-6)}
Generated by NutriFit Health System • Track • Nourish • Be Your Best
`.trim();

    navigator.clipboard.writeText(textReport);
    setCopied(true);
    confetti({ particleCount: 35, spread: 50, origin: { y: 0.6 } });
    setTimeout(() => setCopied(false), 2500);
  };

  const handleDownloadText = () => {
    const textReport = `
=====================================================
🌿 NutriFit - OFFICIAL DAILY HEALTH REPORT
=====================================================
Generated Date: ${formattedDate}
System: NutriFit Personal Health & Nutrition Tracking
Brand Motto: Track • Nourish • Be Your Best

[1] PERSONAL INFORMATION
-----------------------------------------------------
User Name   : ${profile.name}
Age         : ${profile.age} years
Gender      : ${profile.gender}
Height      : ${profile.height} cm
Weight      : ${profile.weight} kg
Body Mass Index (BMI): ${bmiData.bmi} (${bmiData.category})
Ideal Healthy Range : ${bmiData.idealMin} - ${bmiData.idealMax} kg

[2] NUTRITION SUMMARY
-----------------------------------------------------
Calories Consumed : ${totalNutrition.calories} kcal (Target: ${goals.caloriesTarget} kcal)
Protein           : ${totalNutrition.protein} g
Carbohydrates     : ${totalNutrition.carbs} g
Fat               : ${totalNutrition.fat} g

[3] PHYSICAL ACTIVITY LOG
-----------------------------------------------------
${exercises.map(e => `• ${e.exerciseName.padEnd(16)} : ${e.durationMinutes} min  |  ${e.caloriesBurned} kcal burned`).join('\n')}
Total Activity Minutes     : ${totalExerciseMinutes} minutes
Estimated Calories Burned  : ${totalCaloriesBurned} kcal

[4] HYDRATION STATUS
-----------------------------------------------------
Total Water Intake : ${waterL} L / ${goalWaterL} L
Goal Attainment    : ${waterPct}%

[5] SLEEP ANALYSIS
-----------------------------------------------------
Sleep Duration     : ${sleepRecord.hours}h ${sleepRecord.minutes}m
Bedtime / Wake     : ${sleepRecord.bedtime} - ${sleepRecord.wakeTime}
Recommended Goal   : 7 - 9 hours

[6] GOAL ATTAINMENT CHECKLIST
-----------------------------------------------------
Water Intake   : ${waterGoalMet ? '[ PASS ✅ ]' : '[ ATTN ⚠️ ]'}
Daily Exercise : ${exerciseGoalMet ? '[ PASS ✅ ]' : '[ ATTN ⚠️ ]'}
Sleep Goal     : ${sleepGoalMet ? '[ PASS ✅ ]' : '[ ATTN ⚠️ ]'}
Caloric Target : ${nutritionGoalMet ? '[ PASS ✅ ]' : '[ ATTN ⚠️ ]'}

[7] OVERALL DAILY HEALTH SCORE
-----------------------------------------------------
Score: ${dailyHealthScore}%
Evaluator Recommendation:
"Great job! You maintained good activity and hydration today. Try to stay consistent with your nutrition goals."
=====================================================
`.trim();

    const blob = new Blob([textReport], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `NutriFit_Report_${profile.name.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-2 sm:p-4 bg-slate-900/70 backdrop-blur-xs overflow-y-auto">
      <div className="bg-white rounded-2xl max-w-2xl w-full p-3.5 sm:p-6 border border-slate-200 shadow-2xl relative max-h-[96vh] flex flex-col">
        {/* Modal Top Bar */}
        <div className="flex flex-wrap items-center justify-between border-b border-slate-100 pb-3 mb-3 gap-2 no-print">
          <div className="flex items-center gap-2">
            <span className="p-1.5 rounded-lg bg-emerald-100 text-emerald-700">
              <Sparkles className="w-4 h-4 text-emerald-600" />
            </span>
            <span className="text-xs font-bold uppercase tracking-wider text-emerald-800">
              Daily Health Report ⭐
            </span>
          </div>

          <div className="flex items-center gap-1.5 sm:gap-2">
            <button
              onClick={handlePrint}
              id="btn-print-report"
              className="inline-flex items-center gap-1.5 px-2.5 sm:px-3 py-1.5 rounded-lg bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-semibold shadow-xs"
            >
              <Printer className="w-3.5 h-3.5" />
              <span className="hidden xs:inline">Download / </span>
              <span>Print</span>
            </button>

            <button
              onClick={handleCopyReport}
              id="btn-copy-report"
              className="inline-flex items-center gap-1 px-2 sm:px-2.5 py-1.5 rounded-lg bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-semibold"
              title="Copy text summary"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
              <span className="hidden sm:inline">{copied ? 'Copied!' : 'Copy'}</span>
            </button>

            <button
              onClick={handleDownloadText}
              id="btn-download-txt"
              className="p-2 rounded-lg bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs min-w-[36px] flex items-center justify-center"
              title="Download text file"
            >
              <Download className="w-3.5 h-3.5" />
            </button>

            <button
              onClick={onClose}
              className="p-2 rounded-lg hover:bg-slate-100 text-slate-400 hover:text-slate-700 min-w-[36px] flex items-center justify-center"
              aria-label="Close modal"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* PRINTABLE / DISPLAYABLE CLINICAL REPORT BODY */}
        <div
          ref={reportRef}
          className="overflow-y-auto flex-1 pr-1 space-y-4 text-slate-800 bg-white p-4 rounded-xl border border-slate-100 print:p-0 print:border-0"
        >
          {/* Report Header */}
          <div className="border-b-2 border-emerald-600 pb-3.5 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
            <div className="flex items-center gap-3.5">
              <div className="w-16 h-16 sm:w-20 sm:h-20 rounded-2xl overflow-hidden bg-white border border-emerald-200 p-1 shadow-xs shrink-0 flex items-center justify-center">
                <img
                  src="/nutrifit-logo.png"
                  alt="NutriFit Logo"
                  className="w-full h-full object-cover rounded-xl"
                  referrerPolicy="no-referrer"
                />
              </div>
              <div>
                <div className="flex items-center gap-2">
                  <span className="text-2xl font-black text-slate-900">
                    Nutri<span className="text-[#65a30d]">Fit</span>
                  </span>
                  <span className="text-xs px-2.5 py-0.5 rounded-full bg-emerald-100 text-emerald-800 font-bold">
                    Official Health Summary
                  </span>
                </div>
                <p className="text-xs text-slate-500 font-semibold mt-1">
                  Track • Nourish • Be Your Best
                </p>
              </div>
            </div>
            <div className="text-left sm:text-right">
              <div className="text-xs font-bold text-slate-700 uppercase tracking-wider">
                Date: {formattedDate}
              </div>
              <div className="text-[11px] text-slate-500 font-mono">
                Patient / User ID: NFT-2026
              </div>
            </div>
          </div>

          {/* Section 1: Personal Information (Prompt: Age: 20, Height: 165 cm, Weight: 70 kg, BMI: 25.7) */}
          <div className="p-3.5 rounded-xl bg-slate-50/90 border border-slate-200/80">
            <h3 className="text-xs font-bold text-slate-700 uppercase tracking-wider flex items-center gap-1.5 mb-2.5">
              <User className="w-4 h-4 text-slate-600" />
              <span>👤 Personal Information</span>
            </h3>

            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-xs">
              <div className="p-2 bg-white rounded-lg border border-slate-200">
                <span className="text-slate-500 block text-[10px]">Age</span>
                <strong className="text-slate-900 text-sm">{profile.age} years</strong>
              </div>
              <div className="p-2 bg-white rounded-lg border border-slate-200">
                <span className="text-slate-500 block text-[10px]">Height</span>
                <strong className="text-slate-900 text-sm">{profile.height} cm</strong>
              </div>
              <div className="p-2 bg-white rounded-lg border border-slate-200">
                <span className="text-slate-500 block text-[10px]">Weight</span>
                <strong className="text-slate-900 text-sm">{profile.weight} kg</strong>
              </div>
              <div className="p-2 bg-white rounded-lg border border-slate-200">
                <span className="text-slate-500 block text-[10px]">BMI</span>
                <strong className={`text-sm ${bmiData.color}`}>
                  {bmiData.bmi} <span className="text-[10px] font-normal text-slate-500">({bmiData.category})</span>
                </strong>
              </div>
            </div>
          </div>

          {/* Section 2: Nutrition (Prompt: Calories Consumed: 1,650 kcal, Protein: 65 g, Carbs: 210 g, Fat: 52 g) */}
          <div className="p-3.5 rounded-xl bg-slate-50/90 border border-slate-200/80">
            <div className="flex items-center justify-between mb-2">
              <h3 className="text-xs font-bold text-slate-700 uppercase tracking-wider flex items-center gap-1.5">
                <Utensils className="w-4 h-4 text-emerald-600" />
                <span>🥗 Nutrition</span>
              </h3>
              <span className="text-xs font-extrabold text-slate-900">
                Calories Consumed: {totalNutrition.calories.toLocaleString()} kcal
              </span>
            </div>

            <div className="grid grid-cols-3 gap-2 text-center text-xs">
              <div className="p-2 bg-white rounded-lg border border-slate-200">
                <span className="text-emerald-700 font-semibold text-[11px] block">Protein</span>
                <strong className="text-slate-900 text-base">{totalNutrition.protein} g</strong>
              </div>
              <div className="p-2 bg-white rounded-lg border border-slate-200">
                <span className="text-amber-700 font-semibold text-[11px] block">Carbohydrates</span>
                <strong className="text-slate-900 text-base">{totalNutrition.carbs} g</strong>
              </div>
              <div className="p-2 bg-white rounded-lg border border-slate-200">
                <span className="text-rose-700 font-semibold text-[11px] block">Fat</span>
                <strong className="text-slate-900 text-base">{totalNutrition.fat} g</strong>
              </div>
            </div>
          </div>

          {/* Section 3: Activity Breakdown (Prompt: Walking: 45 min — 180 kcal, Yoga: 20 min — 60 kcal... Total: 95 min, 390 kcal) */}
          <div className="p-3.5 rounded-xl bg-slate-50/90 border border-slate-200/80">
            <div className="flex items-center justify-between mb-2">
              <h3 className="text-xs font-bold text-slate-700 uppercase tracking-wider flex items-center gap-1.5">
                <Flame className="w-4 h-4 text-orange-600" />
                <span>🏃 Activity</span>
              </h3>
              <span className="text-xs font-extrabold text-orange-600">
                Total: {totalExerciseMinutes} minutes • {totalCaloriesBurned} kcal burned
              </span>
            </div>

            <div className="bg-white rounded-lg border border-slate-200 p-2.5 divide-y divide-slate-100 text-xs">
              {exercises.length === 0 ? (
                <div className="text-slate-400 py-1 italic">No activities recorded today</div>
              ) : (
                exercises.map(ex => (
                  <div key={ex.id} className="py-1.5 flex justify-between items-center first:pt-0 last:pb-0">
                    <span className="font-semibold text-slate-800">
                      {ex.exerciseName}: <span className="font-normal text-slate-500">{ex.durationMinutes} min</span>
                    </span>
                    <span className="font-bold text-orange-600">
                      {ex.caloriesBurned} kcal
                    </span>
                  </div>
                ))
              )}
            </div>

            <div className="mt-2 text-right text-xs text-slate-600">
              Estimated Calories Burned: <strong className="text-slate-900">{totalCaloriesBurned} kcal</strong>
            </div>
          </div>

          {/* Section 4: Hydration & Sleep (Prompt: Water Intake: 2.0 L / 2.5 L, 80% achieved, Sleep: 7h 30m) */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {/* Hydration */}
            <div className="p-3.5 rounded-xl bg-slate-50/90 border border-slate-200/80">
              <h3 className="text-xs font-bold text-slate-700 uppercase tracking-wider flex items-center gap-1.5 mb-2">
                <Droplets className="w-4 h-4 text-cyan-600" />
                <span>💧 Hydration</span>
              </h3>
              <div className="text-base font-black text-slate-900">
                Water Intake: {waterL} L / {goalWaterL} L
              </div>
              <div className="text-xs font-semibold text-cyan-700 mt-1">
                {waterPct}% of goal achieved
              </div>
            </div>

            {/* Sleep */}
            <div className="p-3.5 rounded-xl bg-slate-50/90 border border-slate-200/80">
              <h3 className="text-xs font-bold text-slate-700 uppercase tracking-wider flex items-center gap-1.5 mb-2">
                <Moon className="w-4 h-4 text-indigo-600" />
                <span>😴 Sleep</span>
              </h3>
              <div className="text-base font-black text-slate-900">
                Sleep Duration: {sleepRecord.hours}h {sleepRecord.minutes}m
              </div>
              <div className="text-xs text-slate-500 mt-1">
                Schedule: {sleepRecord.bedtime} → {sleepRecord.wakeTime}
              </div>
            </div>
          </div>

          {/* Section 5: Daily Goals Checklist (Water: ✅, Exercise: ✅, Sleep: ✅, Nutrition: ⚠️) */}
          <div className="p-3.5 rounded-xl bg-slate-50/90 border border-slate-200/80">
            <h3 className="text-xs font-bold text-slate-700 uppercase tracking-wider flex items-center gap-1.5 mb-2.5">
              <Target className="w-4 h-4 text-slate-700" />
              <span>🎯 Daily Goals</span>
            </h3>

            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-xs">
              <div className="p-2.5 rounded-lg bg-white border border-slate-200 flex items-center justify-between">
                <span className="font-semibold text-slate-700">Water</span>
                <span className="text-base font-bold">{waterGoalMet ? '✅' : '⚠️'}</span>
              </div>
              <div className="p-2.5 rounded-lg bg-white border border-slate-200 flex items-center justify-between">
                <span className="font-semibold text-slate-700">Exercise</span>
                <span className="text-base font-bold">{exerciseGoalMet ? '✅' : '⚠️'}</span>
              </div>
              <div className="p-2.5 rounded-lg bg-white border border-slate-200 flex items-center justify-between">
                <span className="font-semibold text-slate-700">Sleep</span>
                <span className="text-base font-bold">{sleepGoalMet ? '✅' : '⚠️'}</span>
              </div>
              <div className="p-2.5 rounded-lg bg-white border border-slate-200 flex items-center justify-between">
                <span className="font-semibold text-slate-700">Nutrition</span>
                <span className="text-base font-bold">{nutritionGoalMet ? '✅' : '⚠️'}</span>
              </div>
            </div>
          </div>

          {/* Section 6: Overall Progress & Clinical Feedback (Prompt: Daily Health Score: 84%, Feedback message) */}
          <div className="p-4 rounded-xl bg-gradient-to-br from-emerald-500 to-teal-700 text-white shadow-sm">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
              <div>
                <span className="text-xs font-bold uppercase tracking-wider text-emerald-100 flex items-center gap-1.5">
                  <Award className="w-4 h-4" />
                  <span>📊 Overall Progress</span>
                </span>
                <div className="text-3xl font-black mt-1">
                  Daily Health Score: {dailyHealthScore}%
                </div>
              </div>
            </div>

            <div className="mt-3 p-3 bg-white/10 backdrop-blur-xs rounded-lg border border-white/20 text-xs leading-relaxed text-emerald-50 font-medium">
              &ldquo;Great job! You maintained good activity and hydration today. Try to stay consistent with your nutrition goals.&rdquo;
            </div>
          </div>

          {/* Printable Signature Footer */}
          <div className="pt-4 border-t border-slate-200 flex flex-col sm:flex-row items-start sm:items-center justify-between text-[11px] text-slate-600 gap-2">
            <div>
              <span>NutriFit Health System • Track • Nourish • Be Your Best</span>
            </div>
            <div className="text-slate-600 font-mono">
              Evaluated &amp; Verified • ISO Community Health Matrix
            </div>
          </div>
        </div>

        {/* Footer Actions */}
        <div className="border-t border-slate-100 pt-3 mt-2 flex flex-col sm:flex-row items-center justify-between gap-2 no-print">
          <span className="text-xs text-slate-600">
            Click &ldquo;Download / Print&rdquo; to save a PDF or print the official diagnostic sheet.
          </span>

          <div className="flex items-center gap-2 w-full sm:w-auto">
            <button
              onClick={handlePrint}
              className="flex-1 sm:flex-none inline-flex items-center justify-center gap-1.5 px-4 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold shadow-xs transition-colors"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>[Download / Print Daily Report]</span>
            </button>
            <button
              onClick={onClose}
              className="px-4 py-2 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-semibold"
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
